let repos = [
    {
        "id": 293202936,
        "node_id": "MDEwOlJlcG9zaXRvcnkyOTMyMDI5MzY=",
        "name": "fav-program-java",
        "full_name": "myverdict/fav-program-java",
        "private": false,
        "owner": {
            "login": "myverdict",
            "id": 26878263,
            "node_id": "MDQ6VXNlcjI2ODc4MjYz",
            "avatar_url": "https://avatars0.githubusercontent.com/u/26878263?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/myverdict",
            "html_url": "https://github.com/myverdict",
            "followers_url": "https://api.github.com/users/myverdict/followers",
            "following_url": "https://api.github.com/users/myverdict/following{/other_user}",
            "gists_url": "https://api.github.com/users/myverdict/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/myverdict/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/myverdict/subscriptions",
            "organizations_url": "https://api.github.com/users/myverdict/orgs",
            "repos_url": "https://api.github.com/users/myverdict/repos",
            "events_url": "https://api.github.com/users/myverdict/events{/privacy}",
            "received_events_url": "https://api.github.com/users/myverdict/received_events",
            "type": "User",
            "site_admin": false
        },
        "html_url": "https://github.com/myverdict/fav-program-java",
        "description": "Favorite Program for Topic 3 in ITEC 2560",
        "fork": false,
        "url": "https://api.github.com/repos/myverdict/fav-program-java",
        "forks_url": "https://api.github.com/repos/myverdict/fav-program-java/forks",
        "keys_url": "https://api.github.com/repos/myverdict/fav-program-java/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/myverdict/fav-program-java/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/myverdict/fav-program-java/teams",
        "hooks_url": "https://api.github.com/repos/myverdict/fav-program-java/hooks",
        "issue_events_url": "https://api.github.com/repos/myverdict/fav-program-java/issues/events{/number}",
        "events_url": "https://api.github.com/repos/myverdict/fav-program-java/events",
        "assignees_url": "https://api.github.com/repos/myverdict/fav-program-java/assignees{/user}",
        "branches_url": "https://api.github.com/repos/myverdict/fav-program-java/branches{/branch}",
        "tags_url": "https://api.github.com/repos/myverdict/fav-program-java/tags",
        "blobs_url": "https://api.github.com/repos/myverdict/fav-program-java/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/myverdict/fav-program-java/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/myverdict/fav-program-java/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/myverdict/fav-program-java/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/myverdict/fav-program-java/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/myverdict/fav-program-java/languages",
        "stargazers_url": "https://api.github.com/repos/myverdict/fav-program-java/stargazers",
        "contributors_url": "https://api.github.com/repos/myverdict/fav-program-java/contributors",
        "subscribers_url": "https://api.github.com/repos/myverdict/fav-program-java/subscribers",
        "subscription_url": "https://api.github.com/repos/myverdict/fav-program-java/subscription",
        "commits_url": "https://api.github.com/repos/myverdict/fav-program-java/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/myverdict/fav-program-java/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/myverdict/fav-program-java/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/myverdict/fav-program-java/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/myverdict/fav-program-java/contents/{+path}",
        "compare_url": "https://api.github.com/repos/myverdict/fav-program-java/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/myverdict/fav-program-java/merges",
        "archive_url": "https://api.github.com/repos/myverdict/fav-program-java/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/myverdict/fav-program-java/downloads",
        "issues_url": "https://api.github.com/repos/myverdict/fav-program-java/issues{/number}",
        "pulls_url": "https://api.github.com/repos/myverdict/fav-program-java/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/myverdict/fav-program-java/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/myverdict/fav-program-java/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/myverdict/fav-program-java/labels{/name}",
        "releases_url": "https://api.github.com/repos/myverdict/fav-program-java/releases{/id}",
        "deployments_url": "https://api.github.com/repos/myverdict/fav-program-java/deployments",
        "created_at": "2020-09-06T04:27:28Z",
        "updated_at": "2020-09-06T04:35:43Z",
        "pushed_at": "2020-09-06T04:28:05Z",
        "git_url": "git://github.com/myverdict/fav-program-java.git",
        "ssh_url": "git@github.com:myverdict/fav-program-java.git",
        "clone_url": "https://github.com/myverdict/fav-program-java.git",
        "svn_url": "https://github.com/myverdict/fav-program-java",
        "homepage": null,
        "size": 0,
        "stargazers_count": 0,
        "watchers_count": 0,
        "language": "Java",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "forks_count": 0,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 0,
        "license": null,
        "forks": 0,
        "open_issues": 0,
        "watchers": 0,
        "default_branch": "master"
    },
    {
        "id": 295873951,
        "node_id": "MDEwOlJlcG9zaXRvcnkyOTU4NzM5NTE=",
        "name": "ITEC-lab4-assignment",
        "full_name": "myverdict/ITEC-lab4-assignment",
        "private": false,
        "owner": {
            "login": "myverdict",
            "id": 26878263,
            "node_id": "MDQ6VXNlcjI2ODc4MjYz",
            "avatar_url": "https://avatars0.githubusercontent.com/u/26878263?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/myverdict",
            "html_url": "https://github.com/myverdict",
            "followers_url": "https://api.github.com/users/myverdict/followers",
            "following_url": "https://api.github.com/users/myverdict/following{/other_user}",
            "gists_url": "https://api.github.com/users/myverdict/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/myverdict/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/myverdict/subscriptions",
            "organizations_url": "https://api.github.com/users/myverdict/orgs",
            "repos_url": "https://api.github.com/users/myverdict/repos",
            "events_url": "https://api.github.com/users/myverdict/events{/privacy}",
            "received_events_url": "https://api.github.com/users/myverdict/received_events",
            "type": "User",
            "site_admin": false
        },
        "html_url": "https://github.com/myverdict/ITEC-lab4-assignment",
        "description": "Lab 4 - JavaScript Events",
        "fork": false,
        "url": "https://api.github.com/repos/myverdict/ITEC-lab4-assignment",
        "forks_url": "https://api.github.com/repos/myverdict/ITEC-lab4-assignment/forks",
        "keys_url": "https://api.github.com/repos/myverdict/ITEC-lab4-assignment/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/myverdict/ITEC-lab4-assignment/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/myverdict/ITEC-lab4-assignment/teams",
        "hooks_url": "https://api.github.com/repos/myverdict/ITEC-lab4-assignment/hooks",
        "issue_events_url": "https://api.github.com/repos/myverdict/ITEC-lab4-assignment/issues/events{/number}",
        "events_url": "https://api.github.com/repos/myverdict/ITEC-lab4-assignment/events",
        "assignees_url": "https://api.github.com/repos/myverdict/ITEC-lab4-assignment/assignees{/user}",
        "branches_url": "https://api.github.com/repos/myverdict/ITEC-lab4-assignment/branches{/branch}",
        "tags_url": "https://api.github.com/repos/myverdict/ITEC-lab4-assignment/tags",
        "blobs_url": "https://api.github.com/repos/myverdict/ITEC-lab4-assignment/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/myverdict/ITEC-lab4-assignment/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/myverdict/ITEC-lab4-assignment/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/myverdict/ITEC-lab4-assignment/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/myverdict/ITEC-lab4-assignment/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/myverdict/ITEC-lab4-assignment/languages",
        "stargazers_url": "https://api.github.com/repos/myverdict/ITEC-lab4-assignment/stargazers",
        "contributors_url": "https://api.github.com/repos/myverdict/ITEC-lab4-assignment/contributors",
        "subscribers_url": "https://api.github.com/repos/myverdict/ITEC-lab4-assignment/subscribers",
        "subscription_url": "https://api.github.com/repos/myverdict/ITEC-lab4-assignment/subscription",
        "commits_url": "https://api.github.com/repos/myverdict/ITEC-lab4-assignment/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/myverdict/ITEC-lab4-assignment/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/myverdict/ITEC-lab4-assignment/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/myverdict/ITEC-lab4-assignment/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/myverdict/ITEC-lab4-assignment/contents/{+path}",
        "compare_url": "https://api.github.com/repos/myverdict/ITEC-lab4-assignment/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/myverdict/ITEC-lab4-assignment/merges",
        "archive_url": "https://api.github.com/repos/myverdict/ITEC-lab4-assignment/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/myverdict/ITEC-lab4-assignment/downloads",
        "issues_url": "https://api.github.com/repos/myverdict/ITEC-lab4-assignment/issues{/number}",
        "pulls_url": "https://api.github.com/repos/myverdict/ITEC-lab4-assignment/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/myverdict/ITEC-lab4-assignment/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/myverdict/ITEC-lab4-assignment/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/myverdict/ITEC-lab4-assignment/labels{/name}",
        "releases_url": "https://api.github.com/repos/myverdict/ITEC-lab4-assignment/releases{/id}",
        "deployments_url": "https://api.github.com/repos/myverdict/ITEC-lab4-assignment/deployments",
        "created_at": "2020-09-15T23:38:28Z",
        "updated_at": "2020-09-15T23:43:41Z",
        "pushed_at": "2020-09-15T23:43:38Z",
        "git_url": "git://github.com/myverdict/ITEC-lab4-assignment.git",
        "ssh_url": "git@github.com:myverdict/ITEC-lab4-assignment.git",
        "clone_url": "https://github.com/myverdict/ITEC-lab4-assignment.git",
        "svn_url": "https://github.com/myverdict/ITEC-lab4-assignment",
        "homepage": null,
        "size": 4,
        "stargazers_count": 0,
        "watchers_count": 0,
        "language": "HTML",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "forks_count": 0,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 0,
        "license": null,
        "forks": 0,
        "open_issues": 0,
        "watchers": 0,
        "default_branch": "master"
    },
    {
        "id": 296773428,
        "node_id": "MDEwOlJlcG9zaXRvcnkyOTY3NzM0Mjg=",
        "name": "ITEC-lab5-assignment",
        "full_name": "myverdict/ITEC-lab5-assignment",
        "private": false,
        "owner": {
            "login": "myverdict",
            "id": 26878263,
            "node_id": "MDQ6VXNlcjI2ODc4MjYz",
            "avatar_url": "https://avatars0.githubusercontent.com/u/26878263?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/myverdict",
            "html_url": "https://github.com/myverdict",
            "followers_url": "https://api.github.com/users/myverdict/followers",
            "following_url": "https://api.github.com/users/myverdict/following{/other_user}",
            "gists_url": "https://api.github.com/users/myverdict/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/myverdict/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/myverdict/subscriptions",
            "organizations_url": "https://api.github.com/users/myverdict/orgs",
            "repos_url": "https://api.github.com/users/myverdict/repos",
            "events_url": "https://api.github.com/users/myverdict/events{/privacy}",
            "received_events_url": "https://api.github.com/users/myverdict/received_events",
            "type": "User",
            "site_admin": false
        },
        "html_url": "https://github.com/myverdict/ITEC-lab5-assignment",
        "description": "Week 5 - Topic 5 - JavaScript, JSON",
        "fork": false,
        "url": "https://api.github.com/repos/myverdict/ITEC-lab5-assignment",
        "forks_url": "https://api.github.com/repos/myverdict/ITEC-lab5-assignment/forks",
        "keys_url": "https://api.github.com/repos/myverdict/ITEC-lab5-assignment/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/myverdict/ITEC-lab5-assignment/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/myverdict/ITEC-lab5-assignment/teams",
        "hooks_url": "https://api.github.com/repos/myverdict/ITEC-lab5-assignment/hooks",
        "issue_events_url": "https://api.github.com/repos/myverdict/ITEC-lab5-assignment/issues/events{/number}",
        "events_url": "https://api.github.com/repos/myverdict/ITEC-lab5-assignment/events",
        "assignees_url": "https://api.github.com/repos/myverdict/ITEC-lab5-assignment/assignees{/user}",
        "branches_url": "https://api.github.com/repos/myverdict/ITEC-lab5-assignment/branches{/branch}",
        "tags_url": "https://api.github.com/repos/myverdict/ITEC-lab5-assignment/tags",
        "blobs_url": "https://api.github.com/repos/myverdict/ITEC-lab5-assignment/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/myverdict/ITEC-lab5-assignment/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/myverdict/ITEC-lab5-assignment/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/myverdict/ITEC-lab5-assignment/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/myverdict/ITEC-lab5-assignment/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/myverdict/ITEC-lab5-assignment/languages",
        "stargazers_url": "https://api.github.com/repos/myverdict/ITEC-lab5-assignment/stargazers",
        "contributors_url": "https://api.github.com/repos/myverdict/ITEC-lab5-assignment/contributors",
        "subscribers_url": "https://api.github.com/repos/myverdict/ITEC-lab5-assignment/subscribers",
        "subscription_url": "https://api.github.com/repos/myverdict/ITEC-lab5-assignment/subscription",
        "commits_url": "https://api.github.com/repos/myverdict/ITEC-lab5-assignment/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/myverdict/ITEC-lab5-assignment/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/myverdict/ITEC-lab5-assignment/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/myverdict/ITEC-lab5-assignment/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/myverdict/ITEC-lab5-assignment/contents/{+path}",
        "compare_url": "https://api.github.com/repos/myverdict/ITEC-lab5-assignment/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/myverdict/ITEC-lab5-assignment/merges",
        "archive_url": "https://api.github.com/repos/myverdict/ITEC-lab5-assignment/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/myverdict/ITEC-lab5-assignment/downloads",
        "issues_url": "https://api.github.com/repos/myverdict/ITEC-lab5-assignment/issues{/number}",
        "pulls_url": "https://api.github.com/repos/myverdict/ITEC-lab5-assignment/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/myverdict/ITEC-lab5-assignment/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/myverdict/ITEC-lab5-assignment/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/myverdict/ITEC-lab5-assignment/labels{/name}",
        "releases_url": "https://api.github.com/repos/myverdict/ITEC-lab5-assignment/releases{/id}",
        "deployments_url": "https://api.github.com/repos/myverdict/ITEC-lab5-assignment/deployments",
        "created_at": "2020-09-19T02:49:32Z",
        "updated_at": "2020-09-19T03:44:02Z",
        "pushed_at": "2020-09-19T03:44:00Z",
        "git_url": "git://github.com/myverdict/ITEC-lab5-assignment.git",
        "ssh_url": "git@github.com:myverdict/ITEC-lab5-assignment.git",
        "clone_url": "https://github.com/myverdict/ITEC-lab5-assignment.git",
        "svn_url": "https://github.com/myverdict/ITEC-lab5-assignment",
        "homepage": null,
        "size": 9,
        "stargazers_count": 0,
        "watchers_count": 0,
        "language": "JavaScript",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "forks_count": 0,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 0,
        "license": null,
        "forks": 0,
        "open_issues": 0,
        "watchers": 0,
        "default_branch": "master"
    },
    {
        "id": 295852725,
        "node_id": "MDEwOlJlcG9zaXRvcnkyOTU4NTI3MjU=",
        "name": "J2EE",
        "full_name": "myverdict/J2EE",
        "private": false,
        "owner": {
            "login": "myverdict",
            "id": 26878263,
            "node_id": "MDQ6VXNlcjI2ODc4MjYz",
            "avatar_url": "https://avatars0.githubusercontent.com/u/26878263?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/myverdict",
            "html_url": "https://github.com/myverdict",
            "followers_url": "https://api.github.com/users/myverdict/followers",
            "following_url": "https://api.github.com/users/myverdict/following{/other_user}",
            "gists_url": "https://api.github.com/users/myverdict/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/myverdict/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/myverdict/subscriptions",
            "organizations_url": "https://api.github.com/users/myverdict/orgs",
            "repos_url": "https://api.github.com/users/myverdict/repos",
            "events_url": "https://api.github.com/users/myverdict/events{/privacy}",
            "received_events_url": "https://api.github.com/users/myverdict/received_events",
            "type": "User",
            "site_admin": false
        },
        "html_url": "https://github.com/myverdict/J2EE",
        "description": "CSCI 2466 J2EE JSP & Servlets",
        "fork": false,
        "url": "https://api.github.com/repos/myverdict/J2EE",
        "forks_url": "https://api.github.com/repos/myverdict/J2EE/forks",
        "keys_url": "https://api.github.com/repos/myverdict/J2EE/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/myverdict/J2EE/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/myverdict/J2EE/teams",
        "hooks_url": "https://api.github.com/repos/myverdict/J2EE/hooks",
        "issue_events_url": "https://api.github.com/repos/myverdict/J2EE/issues/events{/number}",
        "events_url": "https://api.github.com/repos/myverdict/J2EE/events",
        "assignees_url": "https://api.github.com/repos/myverdict/J2EE/assignees{/user}",
        "branches_url": "https://api.github.com/repos/myverdict/J2EE/branches{/branch}",
        "tags_url": "https://api.github.com/repos/myverdict/J2EE/tags",
        "blobs_url": "https://api.github.com/repos/myverdict/J2EE/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/myverdict/J2EE/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/myverdict/J2EE/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/myverdict/J2EE/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/myverdict/J2EE/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/myverdict/J2EE/languages",
        "stargazers_url": "https://api.github.com/repos/myverdict/J2EE/stargazers",
        "contributors_url": "https://api.github.com/repos/myverdict/J2EE/contributors",
        "subscribers_url": "https://api.github.com/repos/myverdict/J2EE/subscribers",
        "subscription_url": "https://api.github.com/repos/myverdict/J2EE/subscription",
        "commits_url": "https://api.github.com/repos/myverdict/J2EE/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/myverdict/J2EE/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/myverdict/J2EE/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/myverdict/J2EE/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/myverdict/J2EE/contents/{+path}",
        "compare_url": "https://api.github.com/repos/myverdict/J2EE/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/myverdict/J2EE/merges",
        "archive_url": "https://api.github.com/repos/myverdict/J2EE/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/myverdict/J2EE/downloads",
        "issues_url": "https://api.github.com/repos/myverdict/J2EE/issues{/number}",
        "pulls_url": "https://api.github.com/repos/myverdict/J2EE/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/myverdict/J2EE/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/myverdict/J2EE/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/myverdict/J2EE/labels{/name}",
        "releases_url": "https://api.github.com/repos/myverdict/J2EE/releases{/id}",
        "deployments_url": "https://api.github.com/repos/myverdict/J2EE/deployments",
        "created_at": "2020-09-15T21:25:17Z",
        "updated_at": "2020-09-15T21:25:17Z",
        "pushed_at": "2020-09-15T21:25:19Z",
        "git_url": "git://github.com/myverdict/J2EE.git",
        "ssh_url": "git@github.com:myverdict/J2EE.git",
        "clone_url": "https://github.com/myverdict/J2EE.git",
        "svn_url": "https://github.com/myverdict/J2EE",
        "homepage": null,
        "size": 0,
        "stargazers_count": 0,
        "watchers_count": 0,
        "language": null,
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "forks_count": 0,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 0,
        "license": null,
        "forks": 0,
        "open_issues": 0,
        "watchers": 0,
        "default_branch": "master"
    },
    {
        "id": 293595766,
        "node_id": "MDEwOlJlcG9zaXRvcnkyOTM1OTU3NjY=",
        "name": "lab3_assignment",
        "full_name": "myverdict/lab3_assignment",
        "private": false,
        "owner": {
            "login": "myverdict",
            "id": 26878263,
            "node_id": "MDQ6VXNlcjI2ODc4MjYz",
            "avatar_url": "https://avatars0.githubusercontent.com/u/26878263?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/myverdict",
            "html_url": "https://github.com/myverdict",
            "followers_url": "https://api.github.com/users/myverdict/followers",
            "following_url": "https://api.github.com/users/myverdict/following{/other_user}",
            "gists_url": "https://api.github.com/users/myverdict/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/myverdict/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/myverdict/subscriptions",
            "organizations_url": "https://api.github.com/users/myverdict/orgs",
            "repos_url": "https://api.github.com/users/myverdict/repos",
            "events_url": "https://api.github.com/users/myverdict/events{/privacy}",
            "received_events_url": "https://api.github.com/users/myverdict/received_events",
            "type": "User",
            "site_admin": false
        },
        "html_url": "https://github.com/myverdict/lab3_assignment",
        "description": "Week 3 Lab 3 Assignment ITEC 2560",
        "fork": false,
        "url": "https://api.github.com/repos/myverdict/lab3_assignment",
        "forks_url": "https://api.github.com/repos/myverdict/lab3_assignment/forks",
        "keys_url": "https://api.github.com/repos/myverdict/lab3_assignment/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/myverdict/lab3_assignment/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/myverdict/lab3_assignment/teams",
        "hooks_url": "https://api.github.com/repos/myverdict/lab3_assignment/hooks",
        "issue_events_url": "https://api.github.com/repos/myverdict/lab3_assignment/issues/events{/number}",
        "events_url": "https://api.github.com/repos/myverdict/lab3_assignment/events",
        "assignees_url": "https://api.github.com/repos/myverdict/lab3_assignment/assignees{/user}",
        "branches_url": "https://api.github.com/repos/myverdict/lab3_assignment/branches{/branch}",
        "tags_url": "https://api.github.com/repos/myverdict/lab3_assignment/tags",
        "blobs_url": "https://api.github.com/repos/myverdict/lab3_assignment/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/myverdict/lab3_assignment/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/myverdict/lab3_assignment/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/myverdict/lab3_assignment/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/myverdict/lab3_assignment/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/myverdict/lab3_assignment/languages",
        "stargazers_url": "https://api.github.com/repos/myverdict/lab3_assignment/stargazers",
        "contributors_url": "https://api.github.com/repos/myverdict/lab3_assignment/contributors",
        "subscribers_url": "https://api.github.com/repos/myverdict/lab3_assignment/subscribers",
        "subscription_url": "https://api.github.com/repos/myverdict/lab3_assignment/subscription",
        "commits_url": "https://api.github.com/repos/myverdict/lab3_assignment/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/myverdict/lab3_assignment/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/myverdict/lab3_assignment/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/myverdict/lab3_assignment/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/myverdict/lab3_assignment/contents/{+path}",
        "compare_url": "https://api.github.com/repos/myverdict/lab3_assignment/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/myverdict/lab3_assignment/merges",
        "archive_url": "https://api.github.com/repos/myverdict/lab3_assignment/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/myverdict/lab3_assignment/downloads",
        "issues_url": "https://api.github.com/repos/myverdict/lab3_assignment/issues{/number}",
        "pulls_url": "https://api.github.com/repos/myverdict/lab3_assignment/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/myverdict/lab3_assignment/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/myverdict/lab3_assignment/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/myverdict/lab3_assignment/labels{/name}",
        "releases_url": "https://api.github.com/repos/myverdict/lab3_assignment/releases{/id}",
        "deployments_url": "https://api.github.com/repos/myverdict/lab3_assignment/deployments",
        "created_at": "2020-09-07T17:52:16Z",
        "updated_at": "2020-09-15T20:33:11Z",
        "pushed_at": "2020-09-15T20:33:09Z",
        "git_url": "git://github.com/myverdict/lab3_assignment.git",
        "ssh_url": "git@github.com:myverdict/lab3_assignment.git",
        "clone_url": "https://github.com/myverdict/lab3_assignment.git",
        "svn_url": "https://github.com/myverdict/lab3_assignment",
        "homepage": null,
        "size": 14,
        "stargazers_count": 0,
        "watchers_count": 0,
        "language": "HTML",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "forks_count": 0,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 0,
        "license": null,
        "forks": 0,
        "open_issues": 0,
        "watchers": 0,
        "default_branch": "master"
    },
    {
        "id": 292604433,
        "node_id": "MDEwOlJlcG9zaXRvcnkyOTI2MDQ0MzM=",
        "name": "web-week-1-2-html-css",
        "full_name": "myverdict/web-week-1-2-html-css",
        "private": false,
        "owner": {
            "login": "myverdict",
            "id": 26878263,
            "node_id": "MDQ6VXNlcjI2ODc4MjYz",
            "avatar_url": "https://avatars0.githubusercontent.com/u/26878263?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/myverdict",
            "html_url": "https://github.com/myverdict",
            "followers_url": "https://api.github.com/users/myverdict/followers",
            "following_url": "https://api.github.com/users/myverdict/following{/other_user}",
            "gists_url": "https://api.github.com/users/myverdict/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/myverdict/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/myverdict/subscriptions",
            "organizations_url": "https://api.github.com/users/myverdict/orgs",
            "repos_url": "https://api.github.com/users/myverdict/repos",
            "events_url": "https://api.github.com/users/myverdict/events{/privacy}",
            "received_events_url": "https://api.github.com/users/myverdict/received_events",
            "type": "User",
            "site_admin": false
        },
        "html_url": "https://github.com/myverdict/web-week-1-2-html-css",
        "description": null,
        "fork": true,
        "url": "https://api.github.com/repos/myverdict/web-week-1-2-html-css",
        "forks_url": "https://api.github.com/repos/myverdict/web-week-1-2-html-css/forks",
        "keys_url": "https://api.github.com/repos/myverdict/web-week-1-2-html-css/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/myverdict/web-week-1-2-html-css/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/myverdict/web-week-1-2-html-css/teams",
        "hooks_url": "https://api.github.com/repos/myverdict/web-week-1-2-html-css/hooks",
        "issue_events_url": "https://api.github.com/repos/myverdict/web-week-1-2-html-css/issues/events{/number}",
        "events_url": "https://api.github.com/repos/myverdict/web-week-1-2-html-css/events",
        "assignees_url": "https://api.github.com/repos/myverdict/web-week-1-2-html-css/assignees{/user}",
        "branches_url": "https://api.github.com/repos/myverdict/web-week-1-2-html-css/branches{/branch}",
        "tags_url": "https://api.github.com/repos/myverdict/web-week-1-2-html-css/tags",
        "blobs_url": "https://api.github.com/repos/myverdict/web-week-1-2-html-css/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/myverdict/web-week-1-2-html-css/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/myverdict/web-week-1-2-html-css/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/myverdict/web-week-1-2-html-css/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/myverdict/web-week-1-2-html-css/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/myverdict/web-week-1-2-html-css/languages",
        "stargazers_url": "https://api.github.com/repos/myverdict/web-week-1-2-html-css/stargazers",
        "contributors_url": "https://api.github.com/repos/myverdict/web-week-1-2-html-css/contributors",
        "subscribers_url": "https://api.github.com/repos/myverdict/web-week-1-2-html-css/subscribers",
        "subscription_url": "https://api.github.com/repos/myverdict/web-week-1-2-html-css/subscription",
        "commits_url": "https://api.github.com/repos/myverdict/web-week-1-2-html-css/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/myverdict/web-week-1-2-html-css/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/myverdict/web-week-1-2-html-css/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/myverdict/web-week-1-2-html-css/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/myverdict/web-week-1-2-html-css/contents/{+path}",
        "compare_url": "https://api.github.com/repos/myverdict/web-week-1-2-html-css/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/myverdict/web-week-1-2-html-css/merges",
        "archive_url": "https://api.github.com/repos/myverdict/web-week-1-2-html-css/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/myverdict/web-week-1-2-html-css/downloads",
        "issues_url": "https://api.github.com/repos/myverdict/web-week-1-2-html-css/issues{/number}",
        "pulls_url": "https://api.github.com/repos/myverdict/web-week-1-2-html-css/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/myverdict/web-week-1-2-html-css/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/myverdict/web-week-1-2-html-css/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/myverdict/web-week-1-2-html-css/labels{/name}",
        "releases_url": "https://api.github.com/repos/myverdict/web-week-1-2-html-css/releases{/id}",
        "deployments_url": "https://api.github.com/repos/myverdict/web-week-1-2-html-css/deployments",
        "created_at": "2020-09-03T15:11:04Z",
        "updated_at": "2020-09-03T15:11:05Z",
        "pushed_at": "2020-08-22T23:56:50Z",
        "git_url": "git://github.com/myverdict/web-week-1-2-html-css.git",
        "ssh_url": "git@github.com:myverdict/web-week-1-2-html-css.git",
        "clone_url": "https://github.com/myverdict/web-week-1-2-html-css.git",
        "svn_url": "https://github.com/myverdict/web-week-1-2-html-css",
        "homepage": null,
        "size": 1998,
        "stargazers_count": 0,
        "watchers_count": 0,
        "language": null,
        "has_issues": false,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "forks_count": 0,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 0,
        "license": null,
        "forks": 0,
        "open_issues": 0,
        "watchers": 0,
        "default_branch": "master"
    },
    {
        "id": 292604673,
        "node_id": "MDEwOlJlcG9zaXRvcnkyOTI2MDQ2NzM=",
        "name": "week2-examples",
        "full_name": "myverdict/week2-examples",
        "private": false,
        "owner": {
            "login": "myverdict",
            "id": 26878263,
            "node_id": "MDQ6VXNlcjI2ODc4MjYz",
            "avatar_url": "https://avatars0.githubusercontent.com/u/26878263?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/myverdict",
            "html_url": "https://github.com/myverdict",
            "followers_url": "https://api.github.com/users/myverdict/followers",
            "following_url": "https://api.github.com/users/myverdict/following{/other_user}",
            "gists_url": "https://api.github.com/users/myverdict/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/myverdict/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/myverdict/subscriptions",
            "organizations_url": "https://api.github.com/users/myverdict/orgs",
            "repos_url": "https://api.github.com/users/myverdict/repos",
            "events_url": "https://api.github.com/users/myverdict/events{/privacy}",
            "received_events_url": "https://api.github.com/users/myverdict/received_events",
            "type": "User",
            "site_admin": false
        },
        "html_url": "https://github.com/myverdict/week2-examples",
        "description": "Week 2 examples - CSS and Bootstrap",
        "fork": true,
        "url": "https://api.github.com/repos/myverdict/week2-examples",
        "forks_url": "https://api.github.com/repos/myverdict/week2-examples/forks",
        "keys_url": "https://api.github.com/repos/myverdict/week2-examples/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/myverdict/week2-examples/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/myverdict/week2-examples/teams",
        "hooks_url": "https://api.github.com/repos/myverdict/week2-examples/hooks",
        "issue_events_url": "https://api.github.com/repos/myverdict/week2-examples/issues/events{/number}",
        "events_url": "https://api.github.com/repos/myverdict/week2-examples/events",
        "assignees_url": "https://api.github.com/repos/myverdict/week2-examples/assignees{/user}",
        "branches_url": "https://api.github.com/repos/myverdict/week2-examples/branches{/branch}",
        "tags_url": "https://api.github.com/repos/myverdict/week2-examples/tags",
        "blobs_url": "https://api.github.com/repos/myverdict/week2-examples/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/myverdict/week2-examples/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/myverdict/week2-examples/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/myverdict/week2-examples/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/myverdict/week2-examples/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/myverdict/week2-examples/languages",
        "stargazers_url": "https://api.github.com/repos/myverdict/week2-examples/stargazers",
        "contributors_url": "https://api.github.com/repos/myverdict/week2-examples/contributors",
        "subscribers_url": "https://api.github.com/repos/myverdict/week2-examples/subscribers",
        "subscription_url": "https://api.github.com/repos/myverdict/week2-examples/subscription",
        "commits_url": "https://api.github.com/repos/myverdict/week2-examples/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/myverdict/week2-examples/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/myverdict/week2-examples/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/myverdict/week2-examples/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/myverdict/week2-examples/contents/{+path}",
        "compare_url": "https://api.github.com/repos/myverdict/week2-examples/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/myverdict/week2-examples/merges",
        "archive_url": "https://api.github.com/repos/myverdict/week2-examples/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/myverdict/week2-examples/downloads",
        "issues_url": "https://api.github.com/repos/myverdict/week2-examples/issues{/number}",
        "pulls_url": "https://api.github.com/repos/myverdict/week2-examples/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/myverdict/week2-examples/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/myverdict/week2-examples/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/myverdict/week2-examples/labels{/name}",
        "releases_url": "https://api.github.com/repos/myverdict/week2-examples/releases{/id}",
        "deployments_url": "https://api.github.com/repos/myverdict/week2-examples/deployments",
        "created_at": "2020-09-03T15:12:04Z",
        "updated_at": "2020-09-03T15:12:06Z",
        "pushed_at": "2020-08-26T22:43:20Z",
        "git_url": "git://github.com/myverdict/week2-examples.git",
        "ssh_url": "git@github.com:myverdict/week2-examples.git",
        "clone_url": "https://github.com/myverdict/week2-examples.git",
        "svn_url": "https://github.com/myverdict/week2-examples",
        "homepage": null,
        "size": 240,
        "stargazers_count": 0,
        "watchers_count": 0,
        "language": null,
        "has_issues": false,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "forks_count": 0,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 0,
        "license": null,
        "forks": 0,
        "open_issues": 0,
        "watchers": 0,
        "default_branch": "master"
    }
]

// can you print the name of each of your repositories?
console.log("Names of repositories: ");
repos.forEach( function(repo) {
    console.log(repo.name);
})

// can you print the language of each repository?
console.log("\nLanguage of each repository: ");
repos.forEach( function(repo) {
    console.log(repo.language);
})

// Count number of repos
let repoCount = 0;
repos.forEach( function(repo) {
    repoCount++;
})
console.log("\nThe number of repositories: " + repoCount + '\n');

// challenge - can you count the number of repositories in each language?
// include a count for repositories without a language listed
// store those counts in a new object.

// create an empty object for key value pairs
let languageCountsObject = {};      // Java: 1, HTML: 2, null: 3, JavaScript: 1

repos.forEach( function(repo) {
    let language = repo.language;
    // console.log(language);       // debug

    // if(languageCountsObject[language] !== undefined)     // same as below
    if (languageCountsObject[language]) {                    //this is recommended
        // languageCountsObject[language]++;                // condensed version
        let count = languageCountsObject[language];
        count++;
        languageCountsObject[language] = count;
    }
    else {
        languageCountsObject[language] = 1;
    }
})

console.log(languageCountsObject);              // { Java: 1, HTML: 2, JavaScript: 1, null: 3 }

console.log();

console.log(languageCountsObject["Cobol"]);     // undefined
console.log(languageCountsObject["R"]);         // undefined
console.log(languageCountsObject["HTML"]);      // 2
